package cn.edu.buaa.sei.jdat.model;

import java.util.ArrayList;
import java.util.List;
import java.util.HashSet;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : Jar.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//

public class Jar extends DependentNode<Jar> {
	
	public static interface StateChangeListener {
		void stateChange(Jar jar, int state);
	}
	
	private String name;
	private final String uri;
	private int state;
	private Exception exception; // for state ERROR
	public static final int INITIALIZED = 0;
	public static final int LOADING = 1;
	public static final int ERROR = 2;
	public static final int PARSING = 3;
	public static final int BUILDING_STRUCTURE = 5; // new
	public static final int BUILDING_DEPENDENCY = 6; // new
	public static final int READY = 4;
	private List<Package> packages;
	private StateChangeListener listener;
	
	private static final String UKNOWN_JAR_URI = "<unknown>";
	
	public Jar(String uri) {
		this.uri = uri;
		state = INITIALIZED;
		packages = new ArrayList<Package>();
		references = new HashSet<Jar>();
		inverseReferences = new HashSet<Jar>();
		exception = null;
	}
	
	private Jar() {
		uri = UKNOWN_JAR_URI;
		state = READY;
		packages = null;
		references = null;
		inverseReferences = null;
		exception = null;
	}
	
	public static Jar createUnknownJar() {
		return new Jar();
	}
	
	public String getURI() {
		return uri;
	}
	
	public void setState(int state) {
		this.state = state;
		if (listener != null)
			listener.stateChange(this, state);
	}
	
	public int getState() {
		return state;
	}
	
	public void setListener(StateChangeListener listener) {
		this.listener = listener;
	}

	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public Package getPackage(String packageName) {
		for (Package p : packages) {
			if (p.getName().equals(packageName)) return p;
		}
		return null;
	}
	
	public void addPackage(Package p) {
		packages.add(p);
	}
	
	public List<Package> getPackages() {
		return this.packages;
	}
	
	public Exception getException() {
		return exception;
	}
	
	public void setException(Exception exception) {
		this.exception = exception;
	};
	
	public boolean isUnknown() {
		return uri.equals(UKNOWN_JAR_URI);
	}
	
	public void destory() {
		packages.clear();
		packages = null;
	}
	
}
