package cn.edu.buaa.sei.jdat.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : DependentNode.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//
import java.util.Set;

public abstract class DependentNode<T extends DependentNode<T>> {
	protected Set<T> inverseReferences;
	protected Set<T> references;
	
	public void addInverseReference(T node) {
		inverseReferences.add(node);
	}
	
	public void removeInverseReference(T node) {
		inverseReferences.remove(node);
	}
	
	public void addReference(T node) {
		references.add(node);
	}
	
	public void removeReference(T node) {
		references.remove(node);
	}
	
	public Set<T> getReferences() {
		return references;
	}
	
	public Set<T> getInverseReferences() {
		return inverseReferences;
	}
}
