package cn.edu.buaa.sei.jdat.model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : Element.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//

public interface Element {
	public String getName();
	public String getSignature();
	public String getSimpleSignature();
}
