package cn.edu.buaa.sei.jdat;
import java.util.ArrayList;
import java.util.List;

import cn.edu.buaa.sei.jdat.model.Jar;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : JarCollection.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//

public class JarCollection {
	private List<Jar> jars;
	public synchronized void add(Jar jar) {
		jars.add(jar);
	}
	
	public synchronized void remove(Jar jar) {
		jars.remove(jar);
	}
	
	public synchronized int size() {
		return jars.size();
	}
	
	public synchronized Jar get(int index) {
		return jars.get(index);
	}
	
	JarCollection() {
		jars = new ArrayList<Jar>();
	}
	
	public synchronized int indexOf(Jar jar) {
		return jars.indexOf(jar);
	}
	
	public synchronized boolean contains(String url) {
		for (Jar jar : jars) {
			if (jar.getURI().equals(url)) {
				return true;
			}
		}
		return false;
	}
	
	public synchronized Jar[] getAllJars() {
		return jars.toArray(new Jar[0]);
	}
	
}
