package cn.edu.buaa.sei.jdat.model;


//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : Interface.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//

public class Interface extends Type {

	public Type[] getSuperinterfaces() {
		return this.supertypes.toArray(new Type[0]);
	}
	
	public Type[] getSubinterfaces() {
		return this.subtypes.toArray(new Type[0]);
	}
	
	@Override
	public String toString() {
		return "I" + this.getSignature();
	}
	
}
