package cn.edu.buaa.sei.jdat.model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Jar Dependency Analysis Toolkit
//  @ File Name : Member.java
//  @ Date : 2012/1/13
//  @ Author : 
//
//

public abstract class Member implements Element, IModifier {
	private String name;
	private Type owner;
	private String cachedSimpleSignature = null;
	
	private boolean isAbstract = false;
	private boolean isStatic = false;
	private boolean isFinal = false;
	private int accessModifier = IModifier.UKNOWN;
	
	public Type getOwner() {
		return this.owner;
	}
	
	public void setOwner(Type owner) {
		this.owner = owner;
	}
	
	@Override
	public String getName() {
		return this.name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String getSimpleSignature() {
		if (cachedSimpleSignature == null) {
			StringBuilder buf = new StringBuilder(this.owner.getSignature());
			buf.append('.');
			buf.append(this.name);
			cachedSimpleSignature = buf.toString();
		}
		return cachedSimpleSignature;
	}
	
	@Override
	public boolean isAbstract() {
		return isAbstract;
	}
	
	public void setAbstract(boolean isAbstract) {
		this.isAbstract = isAbstract;
	}
	
	@Override
	public boolean isFinal() {
		return isFinal;
	}
	
	public void setFinal(boolean isFinal) {
		this.isFinal = isFinal;
	}
	
	@Override
	public boolean isStatic() {
		return isStatic;
	}
	
	public void setStatic(boolean isStatic) {
		this.isStatic = isStatic;
	}
	
	@Override
	public int getAccessModifiers() {
		return accessModifier;
	}
	
	public void setAccessModifiers(int m) {
		this.accessModifier = m;
	}
}
